# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'FF_PopAlertView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FF_PopAlertView
  
  pod 'SXAlertView'
  
  pod 'KLCPopup'
  pod 'LCActionSheet'
  
  pod 'zhPopupController'
  
  
  target 'FF_PopAlertViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FF_PopAlertViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
